import { Navbar, Products } from "@/components"
import './globals.css'


export const metadata = {
  title: 'Regalo',
  description: 'Generated by create next app and Heimir',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Products />
        {children}
      </body>
    </html>
  )
}
